version: 2.1

parameters:
  run_tests:
    type: boolean
    default: false
  build_release:
    type: boolean
    default: false
  push:
    type: boolean
    default: true
  swift:
    type: enum
    enum: ["build", "test"]
    default: "build"

commands:
  swift:
    description: "Runs swift command"
    parameters:
      command:
        default: --version
        type: string
    steps:
      - run: swift << parameters.command >>

jobs:
  swift:
    docker:
      - image: vapor/swift:5.0.0
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - swift:
          command: << pipeline.parameters.swift >>  

  linux:
    docker:
      - image: vapor/swift:5.0.0
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - swift:
          command: build  
      - when:
          condition: << pipeline.parameters.run_tests >>
          steps:
            - swift:
                command: test  

  linux-release:
    docker:
      - image: vapor/swift:5.0.0
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - swift:
          command: build -c release

workflows:
  version: 2

  swift:
    unless: << pipeline.parameters.push >>
    jobs:
      - swift

  build:
    when: << pipeline.parameters.push >>
    jobs: 
      - linux

  build_release:
    when: << pipeline.parameters.build_release >>
    jobs:
      - linux-release 

