version: 2

jobs:
  linux:
    docker:
      - image: vapor/swift:5.0.0
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build
      - run: swift test

  linux-release:
    docker:
      - image: vapor/swift:5.0.0
    steps:
      - checkout
      - run: apt-get update; apt-get install -y libssl-dev zlib1g-dev
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      - linux-release
      
